### ISSUE TITLE
Position Introslide on Mobile & Tablet Vertical Mode

### ISSUE THREAD

**Issue by FelixWiedemann** [elcheio/felixwiedemann#31]
On Mobile and Tablet in Vertical mode, only a vertical slice of the image is displayed. Is there a way to define on the x-axis which section of the image should be displayed for each image, i.e where the optical center should be ? Not needed for horizonal mode on phones and tablets

**Comment by agorilla** [comment]
Ich habe jetzt für jedes Introslide Bild in der `content/intro/intro.json` zwei neue Parameter eingefügt:

* positionX: Ausrichtung in Prozent vom linken Bildrand 
* positionY: Ausrichtung in Prozent vom oberen Bildrand 

Standard ist 50% bei beiden, d.h. das Bild ist dann horizontal und vertikal zentriert (so wie bisher auch).

Wenn du z.B. `"positionX": "0%"` einträgst für ein Bild, list es komplett links ausgerichtet. Mit den Prozent hast du die Möglichkeit, jedes einzelne Bild so auszurichten, wie du es möchtest.

**Comment by FelixWiedemann** [comment]
Traum, Danke !

**Comment by FelixWiedemann** [comment]
PS: Die Prozentzahl greift nur im Vertikalen Mobile Modus oder, und es bleibt auf laptop und tablet horizontal die Positionierung unverändert ?

**Comment by agorilla** [comment]
Die greifen auf allen Breakpoints, sobald der Screen entweder horizontal oder vertikal zu klein ist. Man kann ja sein Fenster auf Desktop auch kleiner haben. Ich schließe das Issue nun.
