### ISSUE TITLE
Adjust Text Size in Header 'Felix Wiedemann BSC' 

### ISSUE THREAD

**Issue by FelixWiedemann** [elcheio/felixwiedemann#32]
How can I adjust the text size of 'Felix Wiedemann BSC' in header without changing the text size of 'Cinematographer' ? 

If text is currently 24pt what would be the 'rem' equivalent of 25pt ?

Tried to adjust in m-header-scss but created an error, so I had to undo.

**Comment by agorilla** [comment]
@FelixWiedemann Ich habe jetzt mal die FELIX WIEDEMANN Text auf 25px gesetzt und BSC auf 14ox (statt 12)

Wenn du es selbst weiter anpassen möchtest in der m-header.scss
* FELIX WIEDEMANN: Zeile 77
* BSC: Zeile 83

Da kannst du px Werte schreiben, rem generiert der Build dann automatisch daraus.

**Comment by FelixWiedemann** [comment]
Traumhaft, Danke ! 

Nur für mich als Referenz: Welche Größe war 'Felix Wiedemann' vor der Änderung ?

Gehen Komma-werte gehen auch für die px, oder gibt es dann Probleme oder wird unscharf  ? 

Und noch ein Detail ist mir aufgefallen: 'Cinematographer' ist in der Zeile etwas niedriger als 'Felix Wiedemann BSC' und die Navigationsleiste ? Kann man das leicht korrigieren ?

**Comment by agorilla** [comment]
@FelixWiedemann Ich habe jetzt die Schrift auf Ausrichtung "baseline" gesetzt. d.h. die Position sollte jetzt stimmen.

Die 25.5px würde ich nicht empfehlen, da dann extrem krumme rem Werte rauskommen und die Browser meistens eh dann entweder 25 oder 26 Pixel nehmen. ich habe es auf 26px gesetzt jetzt. 1 Pixel ist die kleinste Einheit im Web, man versucht Nachkommastellen zu vermeiden, damit der Browser nicht unnötig runden muss.

**Comment by agorilla** [comment]
Ich schließe das Issue nun
