### ISSUE TITLE
Dark Mode Favicon

### ISSUE THREAD

**Issue by agorilla** [elcheio/felixwiedemann#33]

**Comment by agorilla** [comment]
@FelixWiedemann Ich habe jetzt das Dark Mode Favicon eingebaut. Testweise habe ich die Farben einfach umgekehrt (weiß statt schwarz).

Du kannst es anpassen unter `src/favicon-dark.png`

Hinweis: Die Dark Mode Detection erfolgt nur bei Reload, im Safari musst du ggf jede Seite reloaden um es zu sehen. Das wird stark gecached. Habe den Cache aber mal auf 10 Minuten maximal eingestellt wie json und html.

**Comment by FelixWiedemann** [comment]
Perfect, thanks !
