### ISSUE TITLE
Thumb Layout 2020

### ISSUE THREAD

**Issue by FelixWiedemann** [elcheio/felixwiedemann#35]
Could we have a new thumb (teaser) layout like in the attached images ?

Also jetzt nur ein Projekt pro Zeile, aber mit zwei Thumbnails vom selben Projekt. Zwischen den beiden Thumbnails am besten keine Lücke. Dann eine größere Lücke zur nächsten Zeile (und damit zum nächsten Projekt). 

Der Text mit dem Projektnamen wäre dann entweder über dem linken thumbnail oder in der Mitte über beiden (siehe beide Varianten im Anhang, bin noch unentschlossen).

Textgröße und Thumbnail Größe müsste so wie bisher funktionieren. 

In Mobile Vertikal Mode vielleicht die beiden Thumbnails nebeneinander beibehalten und entsprechend verkleinern ?

![Layout-2020-B-2-small](https://user-images.githubusercontent.com/39480267/88824142-3f108b00-d1c6-11ea-9982-2fb39507c616.png)

![Layout-2020-B-2-Var-small](https://user-images.githubusercontent.com/39480267/88824455-a6c6d600-d1c6-11ea-9470-d83d91658132.png)

**Comment by agorilla** [comment]
Ja, das kann ich einbauen. Angebot schicke ich dir.

Zur Mobile Ansicht: Wenn du beide Bilder nebeneinander hast, wird die Höhe der Bilder relativ klein, ich vermute viel mehr als den Text sieht man dann nicht bei 320px Breite. Sicher dass du das so haben willst?

**Comment by FelixWiedemann** [comment]
Vielen Dank ! Re Mobile Ansicht, ich denke nochmal drüber nach und versuch dass mal in Photoshop zu simulieren und melde mich dann nochmal

**Comment by FelixWiedemann** [comment]
Hi Simon,

Im Anhang nochmal meine aktuellste Mockup Version.

Anmerkungen: 
- wäre super wenn die beiden Thumbs zusammen die ganze Bildschirmbreite nutzen (wie bisher und wie im angehängten Mockup)
- wäre super wenn es einen Parameter gibt der mit dem der Abstand zwischen den Zeilen angepasst wird, so könnte ich dann gucken was am besten aussieht
- ich bin mir noch nicht sicher ob der Text linksbündig im linken Thumb stehen soll oder zentriert über beiden Bildern (wie im angehängten Mockup). Musst Du das jetzt schon wissen oder könnte man das beides leicht probieren wenn das Layout umgesetzt ist ?

Dieses neue Layout funktioniert auf jeden Fall für den Laptop und Tablet Modus (Größe1 und Größe2), die Frage ist wie wir für den Mobile Modus (Größe3) vorgehen... 

Mobile Modus: 

Variante X: Die zwei Thumbs werden einfach kleiner. (hierzu schicke ich Dir eine Email mit Mobile Mockups)
Variante Y: Es wird nur noch ein Thumb pro Projekt angezeigt im kleinsten Modus, ich bräuchte dann einen Parameter für jedes Projekt um zu bestimmen ob Thumb 1 oder Thumb 2 angezeigt wird. 

Wäre Variante Y aufwändiger (und mehr Kosten) als Variante X ? 


![Layout-2020-B-5-Var](https://user-images.githubusercontent.com/39480267/89128141-c6763b00-d4f3-11ea-9932-5406a0b885f7.png)
)
